// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package k8s

import (
	"calmk8s/api/k8s"
)

type ControllerV1 struct{}

func NewV1() k8s.IK8SV1 {
	return &ControllerV1{}
}
