// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"calmk8s/internal/dao/internal"
)

// internalClusterDao is internal type for wrapping internal DAO implements.
type internalClusterDao = *internal.ClusterDao

// clusterDao is the data access object for table ck8s_cluster.
// You can define custom methods on it to extend its functionality as you wish.
type clusterDao struct {
	internalClusterDao
}

var (
	// Cluster is globally public accessible object for table ck8s_cluster operations.
	Cluster = clusterDao{
		internal.NewClusterDao(),
	}
)

// Fill with you ideas below.
