// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"calmk8s/internal/dao/internal"
)

// internalDisksDao is internal type for wrapping internal DAO implements.
type internalDisksDao = *internal.DisksDao

// disksDao is the data access object for table ck8s_disks.
// You can define custom methods on it to extend its functionality as you wish.
type disksDao struct {
	internalDisksDao
}

var (
	// Disks is globally public accessible object for table ck8s_disks operations.
	Disks = disksDao{
		internal.NewDisksDao(),
	}
)

// Fill with you ideas below.
