// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"calmk8s/internal/dao/internal"
)

// internalImagesDao is internal type for wrapping internal DAO implements.
type internalImagesDao = *internal.ImagesDao

// imagesDao is the data access object for table ck8s_images.
// You can define custom methods on it to extend its functionality as you wish.
type imagesDao struct {
	internalImagesDao
}

var (
	// Images is globally public accessible object for table ck8s_images operations.
	Images = imagesDao{
		internal.NewImagesDao(),
	}
)

// Fill with you ideas below.
