// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package pod

import (
	"calmk8s/api/k8s/pod"
)

type ControllerV1 struct{}

func NewV1() pod.IPodV1 {
	return &ControllerV1{}
}
